# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/test-and-build
      with:
        node-version: ${{ matrix.node-version }}

    - name: Deploy
      run: |
        git config --global user.name ${user_name}
        git config --global user.email ${user_email}
        git remote set-url origin https://${github_token}@github.com/${repository}
        echo "REACT_APP_MOCK_API=true" > .env
        npm run deploy
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
